### ISSUE TITLE
The notion and semantics of SFrame “streams” are not well defined

### ISSUE THREAD

**Issue by youennf** [sframe-wg/sframe#100]
Feedback from https://mailarchive.ietf.org/arch/msg/sframe/e9-ZqTTrh_eL6vK2y7OovHt0740/

The notion and semantics of SFrame “streams” are alluded to throughout the document without being well defined. Does the RFC need to define the notion of an SFrame “stream”, consisting of media encrypted all with the same key and cipher suite? It seems like managing such streams is a requirement of the application, but the exact requirements are not spelled out. Here are examples where the notion of a stream comes up:
- a. In section 4.3 it describes a scenario where KIDs are unique to each sender, sort of implying that given an SFrame payload (including the SFrame header) a receiver should be able to decrypt it.
- b. Then in section 4.5 it describes how “In a session that uses multiple media streams, different ciphersuites might be configured for different media streams”, of course implying that if KIDs are per sender, there would need to be some other mechanism to demux from KID → stream, as there could be multiple cipher suites per stream.
- c. This is mentioned head on in section 5.1, where the draft states “In this scheme, it is assumed that receivers have a signal outside of SFrame for which client has sent a given frame, for example the RTP SSRC”

**Comment by bifurcation** [comment]
I don't think we need a notion of SFrame streams.  For almost all purposes, SFrame operations are per-protected-unit, with no higher-level context.  The only sense in which some inter-unit context would be needed is for replay protection, and that can be stated as "within the scope of a single key / KID".

**Comment by alvestrand** [comment]
"Media Stream" is a defined term in RFC 7656 - identical to "RTP Stream".

**Comment by martinthomson** [comment]
Jonathan Lennox asks whether the requirements for signaling that result from this are well defined.  Richard notes that maybe we need to make this clearer.  Signaling needs to include how to identify where keys apply.  Requirements might need to say where the same keys can be used (or where they need to be different).  Agree that we don't need a new concept of "stream" here.

Richard suggests maybe the RTP payload setup might need to be defined.

Bernard Aboba notes for context: The architecture in SCIP are similar to that of SFrame, with e2e protection and key management (key management is handled as a codec).  There are a few differences, but the key management transport aspect that is not described in the SFrame document.  Some of this has been worked through in another document.  (North Atlantic Treaty Organization?)

Jonathan we do need to specify the MLS pieces somewhere.
