### ISSUE TITLE
Incorporate cipher suite in key generation

### ISSUE THREAD

**Issue by bifurcation** [sframe-wg/sframe#128]
```diff
-sframe_secret = HKDF-Extract("SFrame 1.0 Secret " + KID, base_key)
+sframe_secret = HKDF-Extract("SFrame 1.0 Secret " + KID + cipher_suite, base_key)
```

This would solve a couple of problems:

* We could remove the extra HKDF steps in generating encryption/authentication subkeys for the CTR+HMAC cipher suites.  Instead, we would just generate a longer key and split it at the appropriate point.  (We need the cipher suite baked into the KDF so that we get different keys for different tag lengths.)

* We would be slightly more resilient to `base_key` reuse, since you would have to reuse the same `base_key`, `KID`, **and** cipher suite.

The major drawback is that you need a cipher suite code point to use SFrame.  Obviously not a problem for the standard suites, but maybe people want to use unofficial suites.  Probably solvable with some vendor space.

**Comment by mulmarta** [comment]
I like the idea, it simplifies the subkey derivation and including more context always sounds like a good idea. (Even though in general reusing keys with different ciphersuites sounds dangerous.)

If this change does not end up merged, it would be nice to modify the subkey derivation similar to #134

**Comment by bifurcation** [comment]
Interim 2023-09-13:
* RLB: Need to make sure IANA policy is liberal enough that having a code point isn't a bad constraint, e.g., vendor space, FCFS
* Martin: In QUIC, the pattern for vendor-private use is to just pick a valid code point, don't bother registering / telling anyone.  Allows provisional registration for things without specs.
* No objection to editors making a call here.
* TODO(RLB): Reserve private-use code points
