### ISSUE TITLE
Key derivation: label mismatch between draft and reference implementation

### ISSUE THREAD

**Issue by TobTheRock** [sframe-wg/sframe#137]
Hi, 
I am currently trying to update our [sframe implementation](https://github.com/goto-opensource/secure-frame-rs)  to latest draft-03 . There according to the [key derivation section](https://www.ietf.org/archive/id/draft-ietf-sframe-enc-03.html#name-key-derivation). The following labels are used to extract the keys:
```
"SFrame 1.0 Secret key "
"SFrame 1.0 Secret salt "
```
However this is not consistent in your reference implementation, where (e.g. [here](https://github.com/sframe-wg/sframe/blob/main/reference-implementation/src/cipher.rs#L51)) 
```
"SFrame 1.0 key "
"SFrame 1.0 salt "
```
is used.  As a result the generated test vectors do not match the specification.

**Comment by bifurcation** [comment]
Thanks @TobTheRock, good catch.  Looks like we fell out of sync in #134.  I think we probably want the "Secret" there so that the key/salt derivation are specific to the SFrame initialization operation.  cc @mulmarta to confirm

**Comment by mulmarta** [comment]
Oh, yeah, good catch! More separation never hurts so restoring "Secret" makes sense to me.
