### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by bifurcation** [sframe-wg/sframe#151]
There were a few folks who contributed in various ways who should be included in a Contributors section:

* Raphael Robert (@raphaelrobert) and Suhas Nandakumar (@suhasHere) co-wrote draft-barnes-sframe-mls with me, which got folded in here
* Tomas Rigaux (@GhostofCookie) helped un-block a few long-standing issues
* Marta Mularczyk (@mulmarta) contributed some helpful revisions to the HKDF scheme

I may have missed some folks here, feel free to remind me in issue discussion.  I will handle this along with any other WGLC comments.

**Comment by youennf** [comment]
Frederic Jacob provided useful feedback as well, it seems worth to add him as well
