### ISSUE TITLE
Decryption failure behavior

### ISSUE THREAD

**Issue by chris-wood** [sframe-wg/sframe#154]
Currently, what happens when decryption fails is undefined. @bifurcation suggests offline that the packet(s) would be dropped, which seems reasonable. However, I think (a) that behavior should be described and (b) a pointer to the [AEAD limits](https://datatracker.ietf.org/doc/draft-irtf-cfrg-aead-limits) document with some verbiage around how to handle these limits should be added. I could try to prep a PR if that would be helpful.

**Comment by bifurcation** [comment]
PR sounds good to me, thanks!
