### ISSUE TITLE
Inconsistent test vector formatting

### ISSUE THREAD

**Issue by chris-wood** [sframe-wg/sframe#161]
Some hex strings in the test vectors are 0x-prefixed, whereas others are not. For ease of testing, these should be made consistent.

**Comment by bifurcation** [comment]
They are already consistent:

> All values are either numeric or byte strings.  Numeric values are represented
> as hex values, prefixed with `0x`.  Byte strings are represented in hex
> encoding.

**Comment by chris-wood** [comment]
@bifurcation But why have this prefix at all? In my implementation I had to strip off the prefix manually to parse the numbers, which just seems like something we could avoid.

**Comment by bifurcation** [comment]
Why are you parsing the RFC for your implementation?  There's a [JSON file in the repo](https://github.com/sframe-wg/sframe/blob/main/test-vectors/test-vectors.json) which has the numbers already as numbers.
