### ISSUE TITLE
derive_key_salt HKDF hash function

### ISSUE THREAD

**Issue by chris-wood** [sframe-wg/sframe#164]
The hash function to use with HKDF in `derive_key_salt` is currently unspecified. Presumably it's the hash function associated with the cipher suite, but let's make that explicitly clear.

**Comment by bifurcation** [comment]
Huh, I thought that was pretty obvious.  (Where else would the hash come from?)  Happy to consider a PR if you think there's a way to be clearer.

**Comment by chris-wood** [comment]
I agree that it's mostly obvious, but when I read it I did ask myself the question. I figure it's easier to just be explicit here.

**Comment by chris-wood** [comment]
Oh, hah, there's already a line that says what it should be! 

```
The hash function used for HKDF is determined by the cipher suite in use.
```

I just didn't read the entire section. Closing.
