### ISSUE TITLE
Deb Cooley's nits

### ISSUE THREAD

**Issue by martinthomson** [sframe-wg/sframe#191]
Some good stuff here...

Section 4.1, 7.1:  "an E2EE layer over an underlying HBH-encrypted transport". 
It would be clearer to say "an E2EE layer inside a HBH-encrypted transport". 
Obviously the HBH encryption has to be on the outside, right?  I'm assuming
that 'over' means above it in the protocol stack.  If this is a common way to
say this in the IETF, then it is fine (I'll get used to it eventually).

Section 4.4.1, para 2:  Potential re-use of counter values would be reduced in
implementations if the previous counter value was stored (currently next
counter is stored).  The client increments (and stores) at the start vice after
the counter is used. It eliminates a failure to store the next value.  Only my
opinion... If there are many implementations already, then I withdraw the
comment.  Confusion caused mid implementation is worse than leaving it alone.

Section 4.4.2:  If 'sframe_key_label' and 'sframe_salt_label' is 'info' in the
HKDF computation, that should be stated somewhere (or replace 'info' with the
label name).

Section 4.4.3/4.4.4:  Metadata is both encrypted and appended in the clear
(visible to the SFU)?  If so, is the decrypted metatdata compared with the
appended metadata?  Assuming that the metadata is encrypted to provide
integrity... Is this stated somewhere?

Section 4.4.4:  Does the decryptor keep track of CTR state?  If so, what
happens if a CTR value is re-used by the encryptor?  Is the sframe rejected? 
Is there an error sent?  maybe out of band (through the signaling channel)?

Section 4.5.1: For "enc_key_sframe_key[..Nka]" add a comment stating that this
is picking the first Nka bytes.  Also add a comment to "auth_key =
sframe_key[Nka..]" stating to skip Nka bytes to pick the last Nh bytes.  (this
is done as a comment later in the document, so do it here too)

Section 5:  Key management is the responsibility of the application.  And then
there is section 5.1 and 5.2.  Are they options?  Suggestions?  Perhaps add
'Section 5.1 and 5.2 provide two options for partial key management
frameworks.'  (framework might not be the right word, because neither 5.1 nor
5.2 discuss how the base_key gets generated.)

**Comment by bifurcation** [comment]
> Section 4.1, 7.1: "an E2EE layer over an underlying HBH-encrypted transport".
> It would be clearer to say "an E2EE layer inside a HBH-encrypted transport".
> Obviously the HBH encryption has to be on the outside, right? I'm assuming
> that 'over' means above it in the protocol stack. If this is a common way to
> say this in the IETF, then it is fine (I'll get used to it eventually).

I think "over" is idiomatic in the IETF context.  See, for example, the "DNS over HTTPS" or "Media over QUIC" working groups.

> Section 4.4.1, para 2: Potential re-use of counter values would be reduced in
> implementations if the previous counter value was stored (currently next
> counter is stored). The client increments (and stores) at the start vice after
> the counter is used. It eliminates a failure to store the next value. Only my
> opinion... If there are many implementations already, then I withdraw the
> comment. Confusion caused mid implementation is worse than leaving it alone.

This is a fair recommendation, but it actually hasn't really come up in practice.  Typical SFrame implementations are in-memory, not storing counter values.  I added a paragraph to the "Header Value Uniqueness" section, which discusses the application's responsibilities in this regard.

> Section 4.4.2: If 'sframe_key_label' and 'sframe_salt_label' is 'info' in the
> HKDF computation, that should be stated somewhere (or replace 'info' with the
> label name).

Good catch.  I checked the reference implementation, and [this is indeed the case](https://github.com/sframe-wg/sframe/blob/main/reference-implementation/src/cipher.rs#L88-L95).

> Section 4.4.3/4.4.4: Metadata is both encrypted and appended in the clear
> (visible to the SFU)? If so, is the decrypted metatdata compared with the
> appended metadata? Assuming that the metadata is encrypted to provide
> integrity... Is this stated somewhere?

The metadata are not encrypted, only appended to the AAD.  In fact, how the metadata are transmitted is not even specified; it's up to the application to figure out how the endpoints agree on the metadata.  This is discussed in [Section 9.4](https://www.ietf.org/archive/id/draft-ietf-sframe-enc-07.html#name-metadata).

> Section 4.4.4: Does the decryptor keep track of CTR state? If so, what
> happens if a CTR value is re-used by the encryptor? Is the sframe rejected?
> Is there an error sent? maybe out of band (through the signaling channel)?

The WG discussed this and decided not to make a normative requirement, but to provide advice on what implementations might do.  See [Section 9.3](https://www.ietf.org/archive/id/draft-ietf-sframe-enc-07.html#name-anti-replay).

> Section 4.5.1: For "enc_key_sframe_key[..Nka]" add a comment stating that this
> is picking the first Nka bytes. Also add a comment to "auth_key =
> sframe_key[Nka..]" stating to skip Nka bytes to pick the last Nh bytes. (this
> is done as a comment later in the document, so do it here too)

👍 

> Section 5: Key management is the responsibility of the application. And then
> there is section 5.1 and 5.2. Are they options? Suggestions? Perhaps add
> 'Section 5.1 and 5.2 provide two options for partial key management
> frameworks.' (framework might not be the right word, because neither 5.1 nor
> 5.2 discuss how the base_key gets generated.)

5.1 and 5.2 are examples of how these responsibilities might be fulfilled.  They do discuss how the `base_key` is generated: In 5.1 it is ratcheted forward from an initial value (provisioned by the application), and in 5.2 it is derived from an MLS group.

**Comment by debcooley** [comment]
(I'm not going to copy the whole string here, hopefully it is clear)

Thanks for the quick changes.  

4.1:  fine, I'll get used to the IETF way of stating 'over' vs 'inside'.  It is fine, just different that what I'm used to.
4.4.1 and 9.x:  This is ok. Honestly, it is probably too late in the process for this sort of change.  I haven't read the whole of the paragraph 9.x change (Luddite here), As long as it is clear, I'm good.  I'd rather have too many counter changes than too few.  For example, changing it twice in the case of persistent storage is probably better than not changing it at all.
4.4.2: perfect
4.4.3/4.4.4:  fine.  It is an opportunity for an application (which is where you leave it)
4.4.4:  fine.  Same as the previous.
4.5.1:  perfect
5:  this is mostly fine.  If I was an author, I would make it more obvious that 5.1 and 5.2 are examples.   [my terminology is bad, perhaps.  When I said base_key, I meant the initial value that is manipulated into other keys.  Classically, this is the hard part.  And it isn't addressed, which is fine.]

**Comment by bifurcation** [comment]
Re 5 - To be clear, the PR adds text to 5 to be explicit that 5.1 / 5.2 are examples.
