### ISSUE TITLE
Add references for generic payload header extension

### ISSUE THREAD

**Issue by murillo128** [sframe-wg/sframe#2]
> The SFrame payload is constructed by a generic packetizer that splits the E2E encrypted media frame into one or more RTP packet and add the SFrame header to the beginning of the first packet and auth tag to the end of the last packet.

Are the generic payload header extensions already  specified somewhere else that we can refer too?

**Comment by bifurcation** [comment]
Since we've down-scoped the document to focus on the encryption framing, this seems like it's no longer needed?
