### ISSUE TITLE
Mapping between streams to decryption keys

### ISSUE THREAD

**Issue by eomara** [sframe-wg/sframe#32]
As mentioned in the current draft , if the appllication doesn't have the mapping yet between SSRC and users id, the decryptors will try all keys from all users until it finds the mapping. 

However if the stremas are multiplexed by the SFU, the mapping is lost. There are two solutions
1- Use CSRC to write the original SSRC for the multiplexed stream (Already implemented in SFrame) but this will require changes in the SFU
2- Add user Id field in the sFrame payload. There is already a field for KeyId which is incremented everytime the endpoint switched to a new key, we will also add another counter for users (0, 2,,3,.. etc). This means adding extra overhead per packet

**Comment by murillo128** [comment]
Given that we want SFrame/SPacket to be protocol agnostic, both in them of transport and key management, we can't rely on using CSRCs mapping for this.

So we have the following options:
- Signal only the senderId on the SFrame packet, but not the keyId. The receiver would need to keep track of the valid keys for the sender.
- Signal both the senderId and the keyId on the SFrame packet.
- Signal only the keyId and require the senderId to be signaled by the KMS.

I would prefer the first one, as it would also allow to bring back the key ratcheting feature back.

**Comment by bifurcation** [comment]
It seems like the KID field in the SFrame header makes this clear.
