### ISSUE TITLE
V1 feedback: KeyID and substitution

### ISSUE THREAD

**Issue by agouaillard-cosmo** [sframe-wg/sframe#35]
- KeyID and substitution:
I’m aware that you leave it to the higher layer to choose what Key IDs they use. But you suggest counters for keys? That would leak quite bit of metadata and would not be tied to the key itself. Did you consider using a truncated diversified key derivation for deriving the KeyID? 

Credits: Frederic Jacobs

**Comment by martinthomson** [comment]
See #99.  That solution might leak data to the SFU about the choice of keys.  An additional consideration here in terms of how to hide metadata about key choice.  Or maybe we accept that the change of keys leaks.  Does anyone care about that leakage?

Crickets on people caring about the leak.  Could use a PRP to mask this.

Harald cares about the leakage.  We could say that the only thing that is in the spec is the number of bits we need for identifying the key and let applications work out how to construct key IDs.

Richard suggests that bitpacking into key IDs might leak information about what you bit pack (like MLS epoch).  Applications that care can use a different approach for identifying keys (like PRPs).
