### ISSUE TITLE
V1 feedback: If signatures can be stripped, what s the point?

### ISSUE THREAD

**Issue by agouaillard-cosmo** [sframe-wg/sframe#36]
- The use of the signature bit is unclear to me. There is a downgrade attack if the receivers are not aware that they should be expecting signatures to be there. From my read, you include that flag to figure out if you should be adding a signature for that frame. But what’s confusing to me is that you should know ahead of time what frames would have a signature, otherwise, an attacker can just strip that bit and signatures would never be verified. What am I missing?

Credits: Frederic Jacobs

**Comment by murillo128** [comment]
Signatures have been removed from the spec.
