### ISSUE TITLE
V1 feedback: Resigning attacks

### ISSUE THREAD

**Issue by agouaillard-cosmo** [sframe-wg/sframe#37]
- Resigning attacks: It’s unclear how the frames are signed but it seems like unless you have some identity binding in the key derivation, re-signing attacks would be possible.

Credits: Frederic Jacobs

**Comment by bifurcation** [comment]
Since signature facility has been removed from the document, there is no claim of protection of data origin authentication.  Any member of the group can encrypt media using any other member's key.
