### ISSUE TITLE
V1 feedback: Is there or should there be a retry expiration?

### ISSUE THREAD

**Issue by agouaillard-cosmo** [sframe-wg/sframe#41]
- I assume there is a retry expiration, otherwise this could cause some quite confusing UX?
For frames that are failed to decrypt because there is not key available yet, SFrame will buffer them and retries to decrypt them once a key is received. 

Credits: Frederic Jacobs

**Comment by martinthomson** [comment]
Richard: maybe the application can handle this as it is managing the keys, so maybe the SFrame component can signal the error and let the application decide.

**Comment by bifurcation** [comment]
This seems obsolete given that we agreed that there is no mandatory replay protection (#76).
