### ISSUE TITLE
V1 feedback: key ratcheting on joins and rolling on leaves.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [sframe-wg/sframe#42]
- I like the key ratcheting on joins and rolling on leaves. But the following logic seems fragile and can lead to painful situations to debug:
When SFrame decryptor fails to decrypt one of the frames, it automatically ratchets the key forward and retries again until one ratchet succeed or it reaches the maximum allowed ratcheting window 

Credits: Frederic Jacobs.

**Comment by bifurcation** [comment]
The ratcheting logic has been removed.

**Comment by bifurcation** [comment]
I was wrong, there is still ratcheting in there.  May still be obsolete.
