### ISSUE TITLE
V1 feedback: Questions / Clarification request about cipher suite.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [sframe-wg/sframe#46]
- For the ciphersuite:
	- Why CM over CTR acronym in the ciphersuite?
	- What’s the reasoning on the 80-bits and 32-bits MACs?

**Comment by bifurcation** [comment]
... and the 32-bit and 80-bit MACs are to conserve bandwidth in environments where a small probability of forgery is acceptable (typically audio environments).
