### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by martinthomson** [sframe-wg/sframe#80]
With permission, I can set this up so that you get automated gh-pages generation and publication based on tags (rather than manual).

**Comment by youennf** [comment]
That would be good to have.
What do you need to do to make this happen?

**Comment by martinthomson** [comment]
Just your consent.  And a little time.

**Comment by youennf** [comment]
I am interested, editors probably as well.
Let me know how I can help there.

**Comment by martinthomson** [comment]
It looks like we're already rolling according to the actions logs.  The [preview](https://sframe-wg.github.io/sframe/draft-ietf-sframe-enc.html) seems relatively current as well.  Marking this as done.
