### ISSUE TITLE
Test vectors are outdated

### ISSUE THREAD

**Issue by roidanton** [sframe-wg/sframe#85]
Having an implementation based on draft 03, the test vector tests start to fail when the extended key is used and the implementation adds +1 to the header value of `LEN` and `KLEN` (as described in draft 03). When I correctly understand the commit [Restore test vectors instructions](https://github.com/sframe-wg/sframe/commit/ab6f855ee15476b8ffb872f440485090087212c6), they are outdated and it is expected that a test fails which uses the test vectors for a draft 03 implementation. Is that assumption correct?

**Comment by bifurcation** [comment]
Yes, I don't think the test vectors have been updated in a while. We are starting to work toward draft-ietf-sframe-enc-01, so as that starts to firm up, we will update the test vectors to match.

**Comment by murillo128** [comment]
i will update my js implementation when we have the -01 draft, so i will check the test vectors too.

**Comment by TobTheRock** [comment]
I tried updating the generator script, see #106 . I think also there is no test vector for the `AES_CTR_128_HMAC_SHA256_80 ` cipher yet in the latest draft.

**Comment by bifurcation** [comment]
Closing in favor of #133
