### ISSUE TITLE
Should we separate the SFrame specification in smaller specifications

### ISSUE THREAD

**Issue by youennf** [sframe-wg/sframe#86]
As mentioned in feedback given during the review (see https://github.com/sframe-wg/sframe/issues/70), the idea to split the spec in smaller entities was brought up.
For instance, a spec about just the format, and a spec about E2E encryption usage.

**Comment by youennf** [comment]
I started an initial version of a format only spec at https://github.com/youennf/sframe/tree/format-specific-spec.
It is basically the current spec with some parts removed.

**Comment by bifurcation** [comment]
IIRC there is agreement to make draft-ietf-sframe-enc cover only the encryption format.  So we can do that in this repo. As you can see in (for example) #95, my interpretation of this scope is that it's still OK to discuss applying SFrame to packets/frames to help people understand how this encryption format is intended to be used.  We just won't define the concrete mechanisms here.
