### ISSUE TITLE
Is the document talking too much about RTP?

### ISSUE THREAD

**Issue by youennf** [sframe-wg/sframe#96]
Feedback from https://mailarchive.ietf.org/arch/msg/sframe/e9-ZqTTrh_eL6vK2y7OovHt0740/
Throughout the doc there are numerous sections (e.g. 4.4.3, 6) which are very RTP specific, despite a stated goal of the RFC being that SFrame is transport agnostic.

**Comment by youennf** [comment]
At some point, we contemplated having two different documents, one about the format, and one more targeted at the RTP integration. But the main use of SFrame currently is with RTP so it is might also be helpful information for implementors.

Reading section 4.4.3.6, I agree that the metadata section is very RTP specific, which somehow relates to https://github.com/sframe-wg/sframe/issues/63.

Are there other sections that could be improved by making them less RTP specific?

**Comment by bifurcation** [comment]
I agree that this document should be focused on the format, and thus should not contain RTP specifics except as examples.  We should probably do an edit pass to make things more generic.

**Comment by martinthomson** [comment]
Jonathan, yes but... We probably need to have a reasonable confidence that this works for RTP and maybe MPEG-TS before publication.

Richard: a noble aspiration

Bernard: you can test that by implementing SFrame over WebRTC data channel and there you shouldn't need to have anything RTP-specific.  Then you can be confident.

State of the art in implementations demonstrates this.  InsertableStreams shows that this works for cramming stuff in RTP.  In Webex we just transform the payload before and after RFC 3711 protection.  In both cases, the RTP acts as a generic packet transport and don't depend on RTP semantics, mostly (InsertableStreams is more RTP-ish).
