### ISSUE TITLE
 In section 4.3, is KLEN the actual key id length, or key id length minus one, as LEN is?

### ISSUE THREAD

**Issue by youennf** [sframe-wg/sframe#98]
Feedback from https://mailarchive.ietf.org/arch/msg/sframe/e9-ZqTTrh_eL6vK2y7OovHt0740/

 In section 4.3, is KLEN the actual key id length, or key id length minus one, as LEN is?

**Comment by youennf** [comment]
My interpretation of the intent is to bey key id length minus one.

**Comment by youennf** [comment]
https://github.com/sframe-wg/sframe/pull/101

**Comment by bifurcation** [comment]
Closed by #101
